global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:  
        - 'payment-service:9000'
        # - 'registry-service:8761'