spring:
  application:
    name: registry-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
        exclude: loggers
  metrics:
    tags:
      application: registry-service